### ISSUE TITLE
dart:ui/text.dart': Failed assertion: line 1544: '<optimized out>': is not true

### ISSUE THREAD

**Issue by cherrybiu** [JiangJuHong/FlutterTextSpanField#11]
在开发的过程中, 有遇到两个会让程序挂掉的bug, 
1. ios设备上,在@内容前输入拼音, 直接崩溃,循环输出报错
```
======== Exception caught by widgets library =======================================================
The following assertion was thrown building Scrollable(axisDirection: down, physics: null, restorationId: null, dirty, dependencies: [_InheritedTheme, MediaQuery, _EffectiveTickerMode, ScrollConfiguration, _LocalizationsScope-[GlobalKey#59f39]], state: ScrollableState#20ccf(position: ScrollPositionWithSingleContext#825d9(offset: 0.0, range: 0.0..0.0, viewport: 19.0, ScrollableState, BouncingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#9da3b, ScrollDirection.idle), effective physics: BouncingScrollPhysics -> RangeMaintainingScrollPhysics)):
'dart:ui/text.dart': Failed assertion: line 1544: '<optimized out>': is not true.

The relevant error-causing widget was: 
  CustomEditableText-[LabeledGlobalKey<EditableTextState>#3cd19] file:///Users/danhang/work/application/extend-package/FlutterTextSpanField/lib/text_span_field.dart:1010:43
When the exception was thrown, this was the stack: 
#2      TextRange.textInside (dart:ui/text.dart:1544:12)
#3      TextSpanBuilder._buildTextSpanWidget (package:text_span_field/text_span_builder.dart:249:86)
#4      TextSpanBuilder.buildSpan (package:text_span_field/text_span_builder.dart:279:33)
#5      _EditableTextSpan.buildTextSpan (package:text_span_field/custom/custom_editable_text.dart:129:34)
#6      EditableTextState.build.<anonymous closure> (package:flutter/src/widgets/editable_text.dart:2445:27)
...
====================================================================================================

======== Exception caught by rendering library =====================================================
A RenderFlex overflowed by 99896 pixels on the bottom.
The relevant error-causing widget was: 
  Column file:///Users/danhang/work/application/extend-package/FlutterTextSpanField/example/lib/main.dart:79:20
====================================================================================================

======== Exception caught by scheduler library =====================================================
The method 'findRenderObject' was called on null.
Receiver: null
Tried calling: findRenderObject()
====================================================================================================

======== Exception caught by scheduler library =====================================================
The method 'findRenderObject' was called on null.
Receiver: null
Tried calling: findRenderObject()
====================================================================================================
```

2. 如果有多个@内容, 删除第一个@内容, 后面@前的最后一个字符被删除的时候会将后面的@符号也同时删掉, 而且之前的高亮也无效了

**Comment by JiangJuHong** [comment]
两个问题都是ios上出现的吗？android是否有相同问题？

**Comment by cherrybiu** [comment]
第一个问题只在ios上有, 第二个问题是都会出现

**Comment by JiangJuHong** [comment]
好的，近期抽空我会进行排查。

**Comment by cherrybiu** [comment]
复现场景: 正常插入@内容,将光标定位到@内容前, 插入中文, 由于ios的拼音输入法的输入机制,会不断插入拼音,

**Comment by cherrybiu** [comment]
复现场景: 正常插入@内容,将光标定位到@内容前, 插入中文, 

由于ios的拼音输入法的输入机制,会不断插入拼音, 最后选择中文之后, 光标监听器会重新删掉中文, 插入之前的oldText

导致:
'dart:ui/text.dart': Failed assertion: line 1544: '<optimized out>': is not true.

相关日志:

> log格式的顺序都是 oldText -- newText

```
flutter: [LOG] [2021-03-10 02:31:36.863636] 	 控制器监听器 	 @张三 -- w@张三 
 TextSelection(baseOffset: 0, extentOffset: 0, affinity: TextAffinity.downstream, isDirectional: false) 
 TextSelection(baseOffset: 1, extentOffset: 1, affinity: TextAffinity.downstream, isDirectional: false) 
flutter: [堆栈] #2TextSpanBuilder._textControllerListener(package:text_span_field/text_span_builder.dart:41:10)
flutter: [LOG] [2021-03-10 02:31:36.865148] 	 change: 	 @张三 --  w@张三 
flutter: [堆栈] #2TextSpanBuilder._textChangeListener(package:text_span_field/text_span_builder.dart:66:10)
flutter: [LOG] [2021-03-10 02:31:36.866806] 	 添加的内容长度: @张三 -- w@张三 
flutter: [堆栈] #2TextSpanBuilder._addLimit(package:text_span_field/text_span_builder.dart:172:10)
flutter: [LOG] [2021-03-10 02:31:36.869665] 	 range: TextRange(start: 0, end: 1) 
flutter: [堆栈] #2TextSpanBuilder._addLimit(package:text_span_field/text_span_builder.dart:178:10)
flutter: [LOG] [2021-03-10 02:31:36.870872] 	 item--TextRange(start: 0, end: 3) 
flutter: [堆栈] #2TextSpanBuilder._addLimit(package:text_span_field/text_span_builder.dart:187:12)
flutter: [LOG] [2021-03-10 02:31:37.064022] 	 控制器监听器 	 w@张三 -- w w@张三 
 TextSelection(baseOffset: 1, extentOffset: 1, affinity: TextAffinity.downstream, isDirectional: false) 
 TextSelection(baseOffset: 3, extentOffset: 3, affinity: TextAffinity.downstream, isDirectional: false) 
flutter: [堆栈] #2TextSpanBuilder._textControllerListener(package:text_span_field/text_span_builder.dart:41:10)
flutter: [LOG] [2021-03-10 02:31:37.065582] 	 change: 	 w@张三 --  w w@张三 
flutter: [堆栈] #2TextSpanBuilder._textChangeListener(package:text_span_field/text_span_builder.dart:66:10)
flutter: [LOG] [2021-03-10 02:31:37.068377] 	 添加的内容长度: w@张三 -- w w@张三 
flutter: [堆栈] #2TextSpanBuilder._addLimit(package:text_span_field/text_span_builder.dart:172:10)
flutter: [LOG] [2021-03-10 02:31:37.070099] 	 range: TextRange(start: 1, end: 3) 
flutter: [堆栈] #2TextSpanBuilder._addLimit(package:text_span_field/text_span_builder.dart:178:10)
flutter: [LOG] [2021-03-10 02:31:37.071447] 	 item--TextRange(start: 1, end: 4) 
flutter: [堆栈] #2TextSpanBuilder._addLimit(package:text_span_field/text_span_builder.dart:187:12)
flutter: [LOG] [2021-03-10 02:31:37.264753] 	 控制器监听器 	 w w@张三 -- w w w@张三 
 TextSelection(baseOffset: 3, extentOffset: 3, affinity: TextAffinity.downstream, isDirectional: false) 
 TextSelection(baseOffset: 5, extentOffset: 5, affinity: TextAffinity.downstream, isDirectional: false) 
flutter: [堆栈] #2TextSpanBuilder._textControllerListener(package:text_span_field/text_span_builder.dart:41:10)
flutter: [LOG] [2021-03-10 02:31:37.266897] 	 change: 	 w w@张三 --  w w w@张三 
flutter: [堆栈] #2TextSpanBuilder._textChangeListener(package:text_span_field/text_span_builder.dart:66:10)
flutter: [LOG] [2021-03-10 02:31:37.267985] 	 添加的内容长度: w w@张三 -- w w w@张三 
flutter: [堆栈] #2TextSpanBuilder._addLimit(package:text_span_field/text_span_builder.dart:172:10)
flutter: [LOG] [2021-03-10 02:31:37.271013] 	 range: TextRange(start: 3, end: 5) 
flutter: [堆栈] #2TextSpanBuilder._addLimit(package:text_span_field/text_span_builder.dart:178:10)
flutter: [LOG] [2021-03-10 02:31:37.272305] 	 item--TextRange(start: 3, end: 6) 
flutter: [堆栈] #2TextSpanBuilder._addLimit(package:text_span_field/text_span_builder.dart:187:12)
flutter: [LOG] [2021-03-10 02:31:38.879793] 	 控制器监听器 	 w w w@张三 -- 哇哇哇@张三 
 TextSelection(baseOffset: 5, extentOffset: 5, affinity: TextAffinity.downstream, isDirectional: false) 
 TextSelection(baseOffset: 3, extentOffset: 3, affinity: TextAffinity.downstream, isDirectional: false) 
flutter: [堆栈] #2TextSpanBuilder._textControllerListener(package:text_span_field/text_span_builder.dart:41:10)
flutter: [LOG] [2021-03-10 02:31:38.882914] 	 change: 	 w w w@张三 --  哇哇哇@张三 
flutter: [堆栈] #2TextSpanBuilder._textChangeListener(package:text_span_field/text_span_builder.dart:66:10)
flutter: [LOG] [2021-03-10 02:31:38.891224] 	 range--TextRange(start: 3, end: 4) 
flutter: [堆栈] #2TextSpanBuilder._deleteLimit(package:text_span_field/text_span_builder.dart:103:10)
flutter: [LOG] [2021-03-10 02:31:38.893272] 	 deleted--false 
flutter: [堆栈] #2TextSpanBuilder._deleteLimit(package:text_span_field/text_span_builder.dart:113:12)
flutter: [LOG] [2021-03-10 02:31:38.898158] 	 finalText --> w ww@张三 
flutter: [堆栈] #2TextSpanBuilder._deleteLimit(package:text_span_field/text_span_builder.dart:154:10)
flutter: [LOG] [2021-03-10 02:31:38.899250] 	 finalTextSelection --> TextSelection(baseOffset: 3, extentOffset: 3, affinity: TextAffinity.downstream, isDirectional: false) 
flutter: [堆栈] #2TextSpanBuilder._deleteLimit(package:text_span_field/text_span_builder.dart:155:10)
flutter: [LOG] [2021-03-10 02:31:38.904269] 	 控制器监听器 	 哇哇哇@张三 -- 哇哇哇@张三 
 TextSelection(baseOffset: 3, extentOffset: 3, affinity: TextAffinity.downstream, isDirectional: false) 
 TextSelection(baseOffset: 3, extentOffset: 3, affinity: TextAffinity.downstream, isDirectional: false) 
flutter: [堆栈] #2TextSpanBuilder._textControllerListener(package:text_span_field/text_span_builder.dart:41:10)

======== Exception caught by widgets library =======================================================
The following assertion was thrown building Scrollable(axisDirection: down, physics: null, restorationId: null, dirty, dependencies: [_InheritedTheme, MediaQuery, _EffectiveTickerMode, ScrollConfiguration, _LocalizationsScope-[GlobalKey#f27df]], state: ScrollableState#17a79(position: ScrollPositionWithSingleContext#346b2(offset: 0.0, range: 0.0..0.0, viewport: 19.0, ScrollableState, BouncingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#40811, ScrollDirection.idle), effective physics: BouncingScrollPhysics -> RangeMaintainingScrollPhysics)):
'dart:ui/text.dart': Failed assertion: line 1544: '<optimized out>': is not true.

The relevant error-causing widget was: 
  CustomEditableText-[LabeledGlobalKey<EditableTextState>#6c6df] file:///Users/danhang/work/application/extend-package/FlutterTextSpanField/lib/text_span_field.dart:1010:43
When the exception was thrown, this was the stack: 
#2      TextRange.textInside (dart:ui/text.dart:1544:12)
#3      TextSpanBuilder._buildTextSpanWidget (package:text_span_field/text_span_builder.dart:261:86)
#4      TextSpanBuilder.buildSpan (package:text_span_field/text_span_builder.dart:291:33)
#5      _EditableTextSpan.buildTextSpan (package:text_span_field/custom/custom_editable_text.dart:129:34)
#6      EditableTextState.build.<anonymous closure> (package:flutter/src/widgets/editable_text.dart:2445:27)
...
====================================================================================================
```
