### ISSUE TITLE
RangeError (index): Invalid value: Only valid value is 0: 1

### ISSUE THREAD

**Issue by wenboLee** [JiangJuHong/FlutterTextSpanField#6]
@多个用户，再清理之后，会出现抛异常

```
Performing hot restart...
Syncing files to device wenbo...
Restarted application in 711ms.
flutter:  -- @张三
flutter: @张三 -- @张三@张三
flutter: @张三@张三 -- 

======== Exception caught by foundation library ====================================================
The following RangeError was thrown while dispatching notifications for TextEditingController:
RangeError (index): Invalid value: Only valid value is 0: 1

When the exception was thrown, this was the stack: 
#0      List.[] (dart:core-patch/growable_array.dart:177:60)
#1      List.removeAt (dart:core-patch/growable_array.dart:23:22)
#2      TextSpanBuilder._deleteLimit.<anonymous closure> (package:text_span_field/text_span_builder.dart:135:56)
#3      List.forEach (dart:core-patch/growable_array.dart:313:8)
#4      TextSpanBuilder._deleteLimit (package:text_span_field/text_span_builder.dart:135:17)
...
The TextEditingController sending notification was: TextEditingController#6a99f(TextEditingValue(text: ┤├, selection: TextSelection(baseOffset: 0, extentOffset: 0, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1)))
====================================================================================================

======== Exception caught by widgets library =======================================================
Value not in range: 3
The relevant error-causing widget was: 
  CustomEditableText-[LabeledGlobalKey<EditableTextState>#04546] file:///Users/supermonkey/Project/flutter_lib/FlutterTextSpanField/lib/text_span_field.dart:1010:43
====================================================================================================

======== Exception caught by rendering library =====================================================
A RenderFlex overflowed by 99636 pixels on the bottom.
The relevant error-causing widget was: 
  Column file:///Users/supermonkey/Project/flutter_lib/FlutterTextSpanField/example/lib/main.dart:79:20
====================================================================================================

```

**Comment by JiangJuHong** [comment]
你是什么设备？能提供具体的复现步骤吗？

**Comment by wenboLee** [comment]
ios14，iphone7

复现步骤：
在example里，输入多个@用户，点清除按钮

**Comment by JiangJuHong** [comment]
Ios现在暂时有一点问题，我会在近期对它进行修复。

**Comment by wenboLee** [comment]
提个建议，修改官方的源码的话，把源码复制出来就要先提交，不然新增功能部分找不到，我尝试改，实在看不下去😂

**Comment by wenboLee** [comment]
3q (￣▽￣)"

**Comment by JiangJuHong** [comment]
好的，以后会注意。也欢迎PR

**Comment by wenboLee** [comment]
这个问题和平台无关，Android也会有

> Ios现在暂时有一点问题，我会在近期对它进行修复。

**Comment by JiangJuHong** [comment]
好的

**Comment by wenboLee** [comment]
已修复，合并后，验证一下，再顺便发个版吧，(￣▽￣)"

**Comment by JiangJuHong** [comment]
release: v2.0.5
